server:
  port: 8090

spring:
  application:
    name: demo
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: entrega1
    url: jdbc:mysql://localhost:3306/entrega1
    username: root
    password: Password123.