pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/manuelvillara/pep1mingeso']])
                dir("demo"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("demo"){
                    sh "mvn test"
                }
            }
        }
        stage("SonarQube Analysis"){
            steps{
                dir("demo"){
                    sh "mvn clean verify sonar:sonar -Dsonar.projectKey=pep1Mingeso -Dsonar.projectName='pep1Mingeso' -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqp_3f9dff3f2a156f615963a48c754854d4b773f4de"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("demo"){
                    sh "docker build -t manuelvillara/proyecto_docker ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("demo"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]) {
                       sh "docker login -u manuelvillara -p ${dckpass}"
                    }
                    sh "docker push manuelvillara/proyecto_docker"
                }
            }
        }
    }
    post{
        always{
            dir("demo"){
                sh "docker logout"
            }
        }
    }
}